# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rohit/minevally

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rohit/minevally

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rohit/minevally/CMakeFiles /home/rohit/minevally//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rohit/minevally/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named MineVally

# Build rule for target.
MineVally: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MineVally
.PHONY : MineVally

# fast build rule for target.
MineVally/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/build
.PHONY : MineVally/fast

glad.o: glad.c.o
.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i
.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s
.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/glad.c.s
.PHONY : glad.c.s

src/callbacks.o: src/callbacks.cpp.o
.PHONY : src/callbacks.o

# target to build an object file
src/callbacks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/callbacks.cpp.o
.PHONY : src/callbacks.cpp.o

src/callbacks.i: src/callbacks.cpp.i
.PHONY : src/callbacks.i

# target to preprocess a source file
src/callbacks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/callbacks.cpp.i
.PHONY : src/callbacks.cpp.i

src/callbacks.s: src/callbacks.cpp.s
.PHONY : src/callbacks.s

# target to generate assembly for a file
src/callbacks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/callbacks.cpp.s
.PHONY : src/callbacks.cpp.s

src/deps/imgui-1.91.5/backends/imgui_impl_glfw.o: src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.o
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_glfw.o

# target to build an object file
src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.o
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.o

src/deps/imgui-1.91.5/backends/imgui_impl_glfw.i: src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.i
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_glfw.i

# target to preprocess a source file
src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.i
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.i

src/deps/imgui-1.91.5/backends/imgui_impl_glfw.s: src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.s
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_glfw.s

# target to generate assembly for a file
src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.s
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_glfw.cpp.s

src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.o: src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.o
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.o

# target to build an object file
src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.o
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.o

src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.i: src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.i
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.i

# target to preprocess a source file
src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.i
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.i

src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.s: src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.s
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.s
.PHONY : src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.cpp.s

src/deps/imgui-1.91.5/imgui.o: src/deps/imgui-1.91.5/imgui.cpp.o
.PHONY : src/deps/imgui-1.91.5/imgui.o

# target to build an object file
src/deps/imgui-1.91.5/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui.cpp.o
.PHONY : src/deps/imgui-1.91.5/imgui.cpp.o

src/deps/imgui-1.91.5/imgui.i: src/deps/imgui-1.91.5/imgui.cpp.i
.PHONY : src/deps/imgui-1.91.5/imgui.i

# target to preprocess a source file
src/deps/imgui-1.91.5/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui.cpp.i
.PHONY : src/deps/imgui-1.91.5/imgui.cpp.i

src/deps/imgui-1.91.5/imgui.s: src/deps/imgui-1.91.5/imgui.cpp.s
.PHONY : src/deps/imgui-1.91.5/imgui.s

# target to generate assembly for a file
src/deps/imgui-1.91.5/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui.cpp.s
.PHONY : src/deps/imgui-1.91.5/imgui.cpp.s

src/deps/imgui-1.91.5/imgui_draw.o: src/deps/imgui-1.91.5/imgui_draw.cpp.o
.PHONY : src/deps/imgui-1.91.5/imgui_draw.o

# target to build an object file
src/deps/imgui-1.91.5/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui_draw.cpp.o
.PHONY : src/deps/imgui-1.91.5/imgui_draw.cpp.o

src/deps/imgui-1.91.5/imgui_draw.i: src/deps/imgui-1.91.5/imgui_draw.cpp.i
.PHONY : src/deps/imgui-1.91.5/imgui_draw.i

# target to preprocess a source file
src/deps/imgui-1.91.5/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui_draw.cpp.i
.PHONY : src/deps/imgui-1.91.5/imgui_draw.cpp.i

src/deps/imgui-1.91.5/imgui_draw.s: src/deps/imgui-1.91.5/imgui_draw.cpp.s
.PHONY : src/deps/imgui-1.91.5/imgui_draw.s

# target to generate assembly for a file
src/deps/imgui-1.91.5/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui_draw.cpp.s
.PHONY : src/deps/imgui-1.91.5/imgui_draw.cpp.s

src/deps/imgui-1.91.5/imgui_tables.o: src/deps/imgui-1.91.5/imgui_tables.cpp.o
.PHONY : src/deps/imgui-1.91.5/imgui_tables.o

# target to build an object file
src/deps/imgui-1.91.5/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui_tables.cpp.o
.PHONY : src/deps/imgui-1.91.5/imgui_tables.cpp.o

src/deps/imgui-1.91.5/imgui_tables.i: src/deps/imgui-1.91.5/imgui_tables.cpp.i
.PHONY : src/deps/imgui-1.91.5/imgui_tables.i

# target to preprocess a source file
src/deps/imgui-1.91.5/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui_tables.cpp.i
.PHONY : src/deps/imgui-1.91.5/imgui_tables.cpp.i

src/deps/imgui-1.91.5/imgui_tables.s: src/deps/imgui-1.91.5/imgui_tables.cpp.s
.PHONY : src/deps/imgui-1.91.5/imgui_tables.s

# target to generate assembly for a file
src/deps/imgui-1.91.5/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui_tables.cpp.s
.PHONY : src/deps/imgui-1.91.5/imgui_tables.cpp.s

src/deps/imgui-1.91.5/imgui_widgets.o: src/deps/imgui-1.91.5/imgui_widgets.cpp.o
.PHONY : src/deps/imgui-1.91.5/imgui_widgets.o

# target to build an object file
src/deps/imgui-1.91.5/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui_widgets.cpp.o
.PHONY : src/deps/imgui-1.91.5/imgui_widgets.cpp.o

src/deps/imgui-1.91.5/imgui_widgets.i: src/deps/imgui-1.91.5/imgui_widgets.cpp.i
.PHONY : src/deps/imgui-1.91.5/imgui_widgets.i

# target to preprocess a source file
src/deps/imgui-1.91.5/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui_widgets.cpp.i
.PHONY : src/deps/imgui-1.91.5/imgui_widgets.cpp.i

src/deps/imgui-1.91.5/imgui_widgets.s: src/deps/imgui-1.91.5/imgui_widgets.cpp.s
.PHONY : src/deps/imgui-1.91.5/imgui_widgets.s

# target to generate assembly for a file
src/deps/imgui-1.91.5/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/src/deps/imgui-1.91.5/imgui_widgets.cpp.s
.PHONY : src/deps/imgui-1.91.5/imgui_widgets.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/settings.o: src/settings.cpp.o
.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/shader.o: src/shader.cpp.o
.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i
.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s
.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MineVally.dir/build.make CMakeFiles/MineVally.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MineVally"
	@echo "... imgui"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... src/callbacks.o"
	@echo "... src/callbacks.i"
	@echo "... src/callbacks.s"
	@echo "... src/deps/imgui-1.91.5/backends/imgui_impl_glfw.o"
	@echo "... src/deps/imgui-1.91.5/backends/imgui_impl_glfw.i"
	@echo "... src/deps/imgui-1.91.5/backends/imgui_impl_glfw.s"
	@echo "... src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.o"
	@echo "... src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.i"
	@echo "... src/deps/imgui-1.91.5/backends/imgui_impl_opengl3.s"
	@echo "... src/deps/imgui-1.91.5/imgui.o"
	@echo "... src/deps/imgui-1.91.5/imgui.i"
	@echo "... src/deps/imgui-1.91.5/imgui.s"
	@echo "... src/deps/imgui-1.91.5/imgui_draw.o"
	@echo "... src/deps/imgui-1.91.5/imgui_draw.i"
	@echo "... src/deps/imgui-1.91.5/imgui_draw.s"
	@echo "... src/deps/imgui-1.91.5/imgui_tables.o"
	@echo "... src/deps/imgui-1.91.5/imgui_tables.i"
	@echo "... src/deps/imgui-1.91.5/imgui_tables.s"
	@echo "... src/deps/imgui-1.91.5/imgui_widgets.o"
	@echo "... src/deps/imgui-1.91.5/imgui_widgets.i"
	@echo "... src/deps/imgui-1.91.5/imgui_widgets.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

