name: C/C++ Multi-Arch Build

on:
  push:
    branches: [ "main" ]

jobs:
  setup-qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU for cross-arch builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

  build:
    runs-on: ubuntu-latest
    needs: setup-qemu

    strategy:
      matrix:
        arch: [x86_64, aarch64, x86]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build in container for ${{ matrix.arch }}
      run: |
        case "${{ matrix.arch }}" in
          x86_64) platform="linux/amd64" ;;
          aarch64) platform="linux/arm64" ;;
          x86) platform="linux/386" ;;
        esac

        echo "Building for $platform"

        docker run --rm -v $PWD:/src -w /src \
          --platform $platform \
          debian:bookworm bash -c "
            apt-get update &&
            apt-get install -y cmake g++ make libgl1-mesa-dev xorg-dev libglfw3-dev libglm-dev &&
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release &&
            cmake --build build -- -j\$(nproc)
          "

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MineVally-linux-${{ matrix.arch }}
        path: build/MineVally
